"""AgentCore Runtime deploy adapter.

Wraps the `bedrock-agentcore-starter-toolkit` CLI (which handles
ECR + IAM + CodeBuild + CreateAgentRuntime in one step). We generate
the artifact directory (Dockerfile, agent entrypoint, requirements.txt)
matching the contract validated in Spike 1, then shell out to the CLI.

Why subprocess and not direct boto3:
  - Spike 1 already proved the toolkit's CodeBuild path works
    end-to-end. Re-implementing the same flow in boto3 (CreateProject,
    StartBuild, log polling, CreateAgentRuntime, CreateAgentRuntimeEndpoint)
    is ~400 LOC the toolkit already maintains.
  - The toolkit handles ECR auto-create, IAM role auto-create, and
    multi-architecture build correctly.
  - We can replace the subprocess with direct boto3 calls in M2 if we
    need more control (e.g., for VPC-attached deploys or signed images).

What this module owns:
  - Generating the cloudless-flavored entrypoint that bridges
    `@cloudless.agent` classes to the AgentCore HTTP contract.
  - Generating an ARM64 Dockerfile (Spike 1 pattern).
  - Generating a requirements.txt with the right cloudless extras.
  - Invoking `agentcore configure` + `agentcore deploy` in the build dir.
  - Parsing the deploy output to extract the runtime ARN + endpoint URL.

Validated by Spike 1 + Spike 2 (`cloudless-spike-*` AgentCore runtimes).
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass(frozen=True)
class DeploymentResult:
    """What `deploy()` returns after a successful AgentCore deploy."""

    agent_name: str
    runtime_arn: str
    endpoint_arn: str
    ecr_uri: str
    region: str
    protocol: str
    """One of HTTP, MCP, A2A, AGUI (Q6)."""
    build_dir: Path


# Regex for extracting the runtime ARN from agentcore CLI output.
_RUNTIME_ARN_RE = re.compile(
    r"arn:aws:bedrock-agentcore:[a-z0-9-]+:\d+:runtime/[A-Za-z0-9_-]+"
)


# --------------------------------------------------------------------- #
# Template content for the generated artifact files
# --------------------------------------------------------------------- #


_DOCKERFILE_TEMPLATE = """\
# Generated by cloudless. Do not edit by hand.
# AgentCore Runtime requires ARM64 + port {port} + the framework contract.
#
# Python 3.12 (not 3.13) per SPIKE-FINDINGS F16: langchain-aws pulls in
# numpy<2.0 which has no pre-built wheel for linux/arm64+py3.13.
FROM --platform=linux/arm64 public.ecr.aws/docker/library/python:3.12-slim

WORKDIR /app

# Install the locally-built cloudless wheel first (F17: cloudless isn't on
# PyPI yet at v0.x; the deploy adapter builds a wheel and bundles it).
COPY wheelhouse/ ./wheelhouse/
RUN pip install --no-cache-dir ./wheelhouse/cloudless-*.whl

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.py .
COPY user_agent.py .

EXPOSE {port}

CMD ["python", "entrypoint.py"]
"""


_HTTP_ENTRYPOINT_TEMPLATE = '''\
"""Generated by cloudless. Do not edit by hand.

Bridges the user's @cloudless.agent class to the AgentCore HTTP contract:
  POST /invocations  →  agent.query(ctx, prompt)  →  streamed cloudless Chunks
"""
from __future__ import annotations

import json
from typing import Any

from bedrock_agentcore.runtime import BedrockAgentCoreApp

import cloudless
from user_agent import {agent_class}


# Construct the agent once at module-import; the runtime keeps it warm
# across invocations within a microVM session.
_agent = {agent_class}()
app = BedrockAgentCoreApp()


def _build_ctx(request_context: Any) -> cloudless.Context:
    """Materialize a cloudless.Context from AgentCore's RequestContext.

    Spike 2 confirmed AgentCore's authorizer extracts JWT claims when
    JWT inbound auth is configured. M2 will plumb User identity through
    here. For M1 we keep the InMemoryContext stub and just propagate
    the session id.
    """
    session_id = getattr(request_context, "session_id", None) or "default-session"
    return cloudless.InMemoryContext(session_id=session_id)


@app.entrypoint
async def invocations(payload: dict, context: Any) -> dict:
    """AgentCore HTTP entrypoint: POST /invocations."""
    prompt = payload.get("prompt", "")
    ctx = _build_ctx(context)

    chunks: list[dict] = []
    async for chunk in _agent.query(ctx, prompt):
        chunks.append(chunk.model_dump())

    # Convenience: also expose the final text for callers that just want a string
    final_text = "".join(
        c["text"] for c in chunks if c.get("kind") == "text"
    )

    return {{
        "chunks": chunks,
        "final_text": final_text,
        "agent": "{agent_name}",
    }}


if __name__ == "__main__":
    app.run()
'''


_REQUIREMENTS_BASE = """\
# Generated by cloudless. Do not edit by hand.
# (cloudless itself is installed from ./wheelhouse/ before pip reads this — F17.)
bedrock-agentcore>=1.9.0
"""


_FRAMEWORK_REQS = {
    "langgraph": [
        "langgraph>=0.2,<2.0",
        "langchain>=0.3,<2.0",
        "langchain-core>=0.3,<2.0",
        "langchain-aws>=0.2,<2.0",
    ],
    "strands": [
        "strands-agents>=1.39.0",
        "a2a-sdk>=0.3.9,<1.0.0",
        "fastapi>=0.115.0",
    ],
    "adk": ["google-adk>=1.30.0"],
}


# --------------------------------------------------------------------- #
# Public API
# --------------------------------------------------------------------- #


class AgentCoreDeployer:
    """Deploy a cloudless agent to AgentCore Runtime.

    Use the module-level `deploy()` helper for one-shot deploys. Construct
    this class directly for advanced flows (multi-agent batch deploys,
    custom build dirs, etc.).
    """

    def __init__(
        self,
        *,
        region: str = "us-east-1",
        cloudless_version: Optional[str] = None,
        cli_path: Optional[str] = None,
    ) -> None:
        from cloudless._version import __version__ as default_version
        self.region = region
        self.cloudless_version = cloudless_version or default_version
        # Lazy: looked up on first deploy() so artifact generation is testable
        # without bedrock-agentcore-starter-toolkit on PATH.
        self._cli_path_override = cli_path
        self._cli_path_cached: Optional[str] = None

    @property
    def cli_path(self) -> str:
        """Resolve `agentcore` CLI lazily (raises if not on PATH at deploy time)."""
        if self._cli_path_cached is not None:
            return self._cli_path_cached
        path = self._cli_path_override or self._find_agentcore_cli()
        self._cli_path_cached = path
        return path

    @staticmethod
    def _find_agentcore_cli() -> str:
        """Locate the `agentcore` CLI.

        Checks (in order):
          1. PATH (standard shell lookup)
          2. Adjacent to the current Python interpreter (handles unactivated venvs)
        """
        cli = shutil.which("agentcore")
        if cli:
            return cli
        # Fallback: check sys.executable's bin dir — handles `python -m pytest`
        # invoked with a venv's interpreter without the venv being activated.
        venv_bin = Path(sys.executable).parent
        candidate = venv_bin / "agentcore"
        if candidate.is_file():
            return str(candidate)
        raise FileNotFoundError(
            f"Could not find the `agentcore` CLI on PATH or at {candidate}.\n"
            f"Install with: pip install bedrock-agentcore-starter-toolkit"
        )

    # ------------------------------------------------------------------ #
    # Artifact generation
    # ------------------------------------------------------------------ #

    def materialize_artifact(
        self,
        agent_class: type,
        build_dir: Path,
        *,
        framework: Optional[str] = None,
        extra_user_files: Optional[dict[str, str]] = None,
    ) -> Path:
        """Write Dockerfile + entrypoint + requirements + user_agent.py to build_dir.

        Returns the build_dir path.
        """
        if not hasattr(agent_class, "__cloudless_metadata__"):
            raise ValueError(
                f"{agent_class.__name__!r} is not a @cloudless.agent class — "
                f"missing __cloudless_metadata__."
            )

        meta = agent_class.__cloudless_metadata__
        framework = framework or meta.framework or "langgraph"
        # For M1 we always deploy HTTP protocol regardless of meta.interfaces;
        # multi-protocol = multi-deploy (Q6) ships in M2.
        protocol = "HTTP"
        port = 8080 if protocol == "HTTP" else 9000

        build_dir.mkdir(parents=True, exist_ok=True)

        # 1. user_agent.py — copy the user's agent source.
        # If the user provides extra_user_files (e.g., from a project's
        # src/agents/ tree), use those. Otherwise serialize the class
        # source via inspect.
        if extra_user_files:
            for relpath, content in extra_user_files.items():
                target = build_dir / relpath
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content)
        else:
            import inspect
            try:
                source = inspect.getsource(inspect.getmodule(agent_class))
            except OSError as e:
                raise RuntimeError(
                    f"Could not get source for {agent_class.__name__} "
                    f"(inspect.getsource failed: {e}). Pass extra_user_files."
                ) from e
            (build_dir / "user_agent.py").write_text(source)

        # 2. entrypoint.py
        entrypoint = _HTTP_ENTRYPOINT_TEMPLATE.format(
            agent_class=agent_class.__name__,
            agent_name=meta.name,
        )
        (build_dir / "entrypoint.py").write_text(entrypoint)

        # 3. requirements.txt
        reqs = [_REQUIREMENTS_BASE]
        if framework in _FRAMEWORK_REQS:
            reqs.extend(_FRAMEWORK_REQS[framework])
        (build_dir / "requirements.txt").write_text("\n".join(reqs) + "\n")

        # 4. Dockerfile
        (build_dir / "Dockerfile").write_text(_DOCKERFILE_TEMPLATE.format(port=port))

        # 5. wheelhouse/cloudless-*.whl — build the cloudless wheel from the
        #    source tree this code is running from so the container can
        #    `pip install ./wheelhouse/cloudless-*.whl`. F17 — pre-PyPI workaround.
        self._build_cloudless_wheel(build_dir / "wheelhouse")

        return build_dir

    @staticmethod
    def _build_cloudless_wheel(wheelhouse: Path) -> None:
        """Build cloudless wheel into wheelhouse/. F17."""
        import cloudless as cl_module
        cloudless_root = Path(cl_module.__file__).parent.parent.parent
        # If running from an editable install, this points to the repo root with pyproject.toml
        if not (cloudless_root / "pyproject.toml").is_file():
            raise RuntimeError(
                f"Can't find cloudless source root with pyproject.toml at {cloudless_root}. "
                f"F17 workaround needs cloudless installed editable from a repo. "
                f"Once cloudless is on PyPI, this won't be necessary."
            )
        wheelhouse.mkdir(parents=True, exist_ok=True)
        # Use `pip wheel --no-deps` from the same Python the user is running with.
        proc = subprocess.run(
            [sys.executable, "-m", "pip", "wheel", "--no-deps",
             "--wheel-dir", str(wheelhouse), str(cloudless_root)],
            capture_output=True, text=True, check=False,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"Failed to build cloudless wheel:\n"
                f"stdout: {proc.stdout[-1000:]}\nstderr: {proc.stderr[-1000:]}"
            )

    # ------------------------------------------------------------------ #
    # Deploy
    # ------------------------------------------------------------------ #

    def deploy(
        self,
        agent_class: type,
        *,
        build_dir: Optional[Path] = None,
        framework: Optional[str] = None,
        extra_user_files: Optional[dict[str, str]] = None,
    ) -> DeploymentResult:
        """Materialize artifact + invoke agentcore configure + deploy. Returns ARN."""
        meta = agent_class.__cloudless_metadata__
        # The agentcore CLI requires the name to be a valid Python identifier;
        # convert kebab-case to snake_case for safety.
        runtime_name = meta.name.replace("-", "_")

        if build_dir is None:
            build_dir = Path(".cloudless") / "build" / runtime_name
        build_dir = build_dir.resolve()

        self.materialize_artifact(
            agent_class, build_dir,
            framework=framework, extra_user_files=extra_user_files,
        )

        env = self._toolkit_env()

        # 1. configure
        self._run_cli(
            [self.cli_path, "configure", "--create",
             "--entrypoint", "entrypoint.py",
             "--name", runtime_name,
             "--protocol", "HTTP",
             "--runtime", "PYTHON_3_12",   # match Dockerfile base (F16)
             "--region", self.region,
             "--requirements-file", "requirements.txt",
             "--disable-memory",
             "--non-interactive"],
            cwd=build_dir, env=env,
        )

        # 2. Flip ECR + S3 auto-create on the generated yaml (Spike 1 pattern)
        self._enable_autocreate(build_dir / ".bedrock_agentcore.yaml")

        # 3. deploy
        deploy_out = self._run_cli(
            [self.cli_path, "deploy",
             "--agent", runtime_name,
             "--auto-update-on-conflict"],
            cwd=build_dir, env=env, capture=True,
        )

        # 4. Parse the runtime ARN from CLI output
        m = _RUNTIME_ARN_RE.search(deploy_out)
        if not m:
            raise RuntimeError(
                "Could not find runtime ARN in agentcore deploy output. "
                "Tail:\n" + "\n".join(deploy_out.splitlines()[-30:])
            )
        runtime_arn = m.group(0)

        # Endpoint is always /runtime-endpoint/DEFAULT on first deploy
        endpoint_arn = f"{runtime_arn}/runtime-endpoint/DEFAULT"

        # ECR URI is the line after `ECR URI:`; best-effort parse
        ecr_uri = ""
        for line in deploy_out.splitlines():
            if "ECR URI:" in line:
                ecr_uri = line.split("ECR URI:", 1)[1].strip().rstrip("│ ").strip()
                break

        return DeploymentResult(
            agent_name=runtime_name,
            runtime_arn=runtime_arn,
            endpoint_arn=endpoint_arn,
            ecr_uri=ecr_uri,
            region=self.region,
            protocol="HTTP",
            build_dir=build_dir,
        )

    # ------------------------------------------------------------------ #
    # Helpers
    # ------------------------------------------------------------------ #

    @staticmethod
    def _toolkit_env() -> dict[str, str]:
        """Pass through current env + silence the CLI migration banner."""
        env = dict(os.environ)
        env.setdefault("AGENTCORE_SUPPRESS_RECOMMENDATION", "1")
        return env

    @staticmethod
    def _run_cli(argv: list[str], *, cwd: Path, env: dict[str, str],
                 capture: bool = False) -> str:
        """Run a subprocess; raise on non-zero exit; optionally return stdout."""
        proc = subprocess.run(
            argv, cwd=cwd, env=env,
            stdout=subprocess.PIPE if capture else None,
            stderr=subprocess.STDOUT if capture else None,
            text=True, check=False,
        )
        out = proc.stdout or ""
        if proc.returncode != 0:
            raise RuntimeError(
                f"command failed: {' '.join(argv)}\n"
                f"exit code: {proc.returncode}\n"
                f"output (tail):\n" + "\n".join(out.splitlines()[-30:])
            )
        return out

    @staticmethod
    def _enable_autocreate(yaml_path: Path) -> None:
        """Spike 1 pattern: agentcore configure doesn't enable auto-create by default."""
        text = yaml_path.read_text()
        text = text.replace("ecr_auto_create: false", "ecr_auto_create: true")
        text = text.replace("s3_auto_create: false", "s3_auto_create: true")
        yaml_path.write_text(text)


def deploy(
    agent_class: type,
    *,
    region: str = "us-east-1",
    build_dir: Optional[Path] = None,
    framework: Optional[str] = None,
    extra_user_files: Optional[dict[str, str]] = None,
) -> DeploymentResult:
    """One-shot AgentCore deploy. Returns DeploymentResult with the ARN."""
    return AgentCoreDeployer(region=region).deploy(
        agent_class,
        build_dir=build_dir,
        framework=framework,
        extra_user_files=extra_user_files,
    )
