"""Unit tests for the AgentCore deploy adapter — artifact materialization only.

The full deploy() call shells out to the `agentcore` CLI which requires
AWS creds + CodeBuild and is exercised in the integration test. Here we
test the pure-Python artifact-generation path.
"""
from __future__ import annotations

import tempfile
from pathlib import Path

import pytest

import cloudless
from cloudless.adapters.aws.agentcore import (
    _FRAMEWORK_REQS,
    AgentCoreDeployer,
)


@cloudless.agent(name="unit-test-agent", framework="langgraph")
class _DummyAgent(cloudless.Agent):
    async def query(self, ctx, prompt):
        yield cloudless.TextChunk(text="hi")


@pytest.fixture
def tmp_build():
    with tempfile.TemporaryDirectory() as td:
        yield Path(td)


class TestMaterializeArtifact:
    def test_writes_all_required_files(self, tmp_build):
        d = AgentCoreDeployer()
        out = d.materialize_artifact(_DummyAgent, tmp_build,
                                     extra_user_files={"user_agent.py": "# stub"})
        for name in ("Dockerfile", "entrypoint.py", "requirements.txt", "user_agent.py"):
            assert (out / name).is_file(), f"missing {name}"

    def test_dockerfile_pins_arm64_and_port_8080(self, tmp_build):
        d = AgentCoreDeployer()
        d.materialize_artifact(_DummyAgent, tmp_build,
                               extra_user_files={"user_agent.py": "# stub"})
        df = (tmp_build / "Dockerfile").read_text()
        # Per F12 + Spike 1 — AgentCore HTTP contract
        assert "linux/arm64" in df
        assert "EXPOSE 8080" in df
        assert "python:3.12" in df  # F16: 3.12 not 3.13 due to numpy/arm64 wheels

    def test_entrypoint_references_agent_class(self, tmp_build):
        d = AgentCoreDeployer()
        d.materialize_artifact(_DummyAgent, tmp_build,
                               extra_user_files={"user_agent.py": "# stub"})
        ep = (tmp_build / "entrypoint.py").read_text()
        assert "from user_agent import _DummyAgent" in ep
        assert "BedrockAgentCoreApp" in ep
        assert "@app.entrypoint" in ep
        assert "cloudless.InMemoryContext" in ep

    def test_requirements_includes_framework_pins(self, tmp_build):
        d = AgentCoreDeployer()
        d.materialize_artifact(_DummyAgent, tmp_build,
                               framework="langgraph",
                               extra_user_files={"user_agent.py": "# stub"})
        reqs = (tmp_build / "requirements.txt").read_text()
        # F17: cloudless itself isn't in requirements.txt; it's installed
        # from the bundled wheel by the Dockerfile.
        assert "cloudless" not in reqs.replace("# Generated by cloudless", "").replace("cloudless itself", "")
        assert "bedrock-agentcore" in reqs
        for langgraph_pin in _FRAMEWORK_REQS["langgraph"]:
            assert langgraph_pin in reqs

    def test_wheelhouse_contains_cloudless_wheel(self, tmp_build):
        """F17: deploy adapter builds + bundles a local cloudless wheel."""
        d = AgentCoreDeployer()
        d.materialize_artifact(_DummyAgent, tmp_build,
                               extra_user_files={"user_agent.py": "# stub"})
        wheels = list((tmp_build / "wheelhouse").glob("cloudless-*.whl"))
        assert wheels, "cloudless wheel must be bundled for the container build"

    def test_strands_framework_pins_a2a_sdk(self, tmp_build):
        d = AgentCoreDeployer()
        d.materialize_artifact(_DummyAgent, tmp_build,
                               framework="strands",
                               extra_user_files={"user_agent.py": "# stub"})
        reqs = (tmp_build / "requirements.txt").read_text()
        # F3 pin for v0.3 A2A lane
        assert "a2a-sdk>=0.3.9,<1.0.0" in reqs
        assert "strands-agents" in reqs

    def test_rejects_class_without_decorator(self, tmp_build):
        class Bare(cloudless.Agent):
            async def query(self, ctx, prompt):
                yield cloudless.TextChunk(text="")
        d = AgentCoreDeployer()
        with pytest.raises(ValueError, match=r"not a @cloudless\.agent class"):
            d.materialize_artifact(Bare, tmp_build,
                                   extra_user_files={"user_agent.py": "# stub"})

    def test_extra_user_files_can_override_user_agent(self, tmp_build):
        d = AgentCoreDeployer()
        d.materialize_artifact(_DummyAgent, tmp_build,
                               extra_user_files={
                                   "user_agent.py": "# my custom source\n",
                                   "helpers/util.py": "X = 1\n",
                               })
        assert (tmp_build / "user_agent.py").read_text().startswith("# my custom source")
        assert (tmp_build / "helpers/util.py").read_text() == "X = 1\n"


class TestPublicSurface:
    def test_top_level_imports(self):
        from cloudless.adapters.aws import AgentCoreDeployer, DeploymentResult, deploy
        assert AgentCoreDeployer is not None
        assert DeploymentResult is not None
        assert callable(deploy)
